---

# run pre-update scripts

- name: Checking if pre_update.sh script exists
  stat:
    path: /opt/updates/pre_update.sh
  register: pre_update_script

- name: Running pre update script
  command: sh /opt/updates/pre_update.sh
  when: pre_update_script.stat.exists == true
  become: yes
  ignore_errors: no

# install all available updates

- name: Installing all available updates
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes

# Check if reboot is required

- name: checking if reboot-required file exists
  stat:
    path: /var/run/reboot-required
  register: reboot

- name: reboot if required
  reboot:
    reboot_timeout: 1200
  when: reboot.stat.exists == true
  become: yes

# run post-update scripts

- name: Checking if post_update.sh script exists
  stat:
    path: /opt/updates/post_update.sh
  register: post_update_script
 
- name: Running post update script
  command: sh /opt/updates/post_update.sh
  when:
    - post_update_script.stat.exists == true
  become: yes

