---

# Install dnf-utils which is required to check if a reboot is required after updates have completed.

- name: Installing dnf-utils package
  yum:
    name: dnf-utils
    state: latest
  become: yes

# Run pre-update scripts.

- name: Checking if pre_update.sh script exists
  stat:
    path: /opt/updates/pre_update.sh
  register: pre_update_script

- name: Running pre update script
  command: sh /opt/updates/pre_update.sh
  when: pre_update_script.stat.exists == true
  become: yes
  ignore_errors: no

# Install all available updates.

- name: Installing all available updates
  dnf:
    name: '*'
    state: latest
  become: yes

# Check if reboot is required.

- name: checking if reboot is required
  shell: needs-restarting  -r
  register: reboot
  failed_when: reboot.rc != 1 and reboot.rc != 0

# Reboot the host if reboot return code is true.

- name: reboot if required
  reboot:
    reboot_timeout: 1200
  when: reboot.rc == 1
  become: yes

# run post-update scripts

- name: Checking if post_update.sh script exists
  stat:
    path: /opt/updates/post_update.sh
  register: post_update_script
 
- name: Running post update script
  command: sh /opt/updates/post_update.sh
  when:
    - post_update_script.stat.exists == true
  become: yes

