---

# CentOS & RedHat 8+ | Fedora 30+

- include_tasks: dnf_update.yml
  when:
  - (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
  - ansible_distribution_major_version >= "8"

# Debian 10+

- include_tasks: apt_update.yml
  when:
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version >= "10"  

# Windows OSes

- include_tasks: windows_update.yml
  when: ansible_os_family == "Windows"

